# Generated by Django 4.2 on 2025-04-19 19:35

import dashboard.mixins.draftables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0037_merge_20231130_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftAnswerTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_draft_model.<locals>.DraftMixin, 'dashboard.answertranslation'),
        ),
        migrations.CreateModel(
            name='DraftArticleTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_draft_model.<locals>.DraftMixin, 'dashboard.articletranslation'),
        ),
        migrations.CreateModel(
            name='DraftTranslatedQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_draft_model.<locals>.DraftMixin, 'dashboard.translatedquestion'),
        ),
        migrations.CreateModel(
            name='PublishedAnswerTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_published_model.<locals>.PublishedMixin, 'dashboard.answertranslation'),
        ),
        migrations.CreateModel(
            name='PublishedArticleTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_published_model.<locals>.PublishedMixin, 'dashboard.articletranslation'),
        ),
        migrations.CreateModel(
            name='PublishedTranslatedQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_published_model.<locals>.PublishedMixin, 'dashboard.translatedquestion'),
        ),
        migrations.CreateModel(
            name='SubmittedAnswerTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_submitted_model.<locals>.SubmittedMixin, 'dashboard.answertranslation'),
        ),
        migrations.CreateModel(
            name='SubmittedArticleTranslation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_submitted_model.<locals>.SubmittedMixin, 'dashboard.articletranslation'),
        ),
        migrations.CreateModel(
            name='SubmittedTranslatedQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(dashboard.mixins.draftables.DraftableModel.get_submitted_model.<locals>.SubmittedMixin, 'dashboard.translatedquestion'),
        ),
        migrations.AlterField(
            model_name='answertranslation',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translatedquestion',
            name='translated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
